export default {
    GET_SCREAMS: "GET_SCREAMS",
    LOADING: "LOADING",
    LIKE_SCREAM: "LIKE_SCREAM",
    UNLIKE_SCREAM: "UNLIKE_SCREAM",
    SEND_TO_CONTEXT: "SEND_TO_CONTEXT",
    DELETE_SCREAM: "DELETE_SCREAM",
    CLOSE_MODAL: "CLOSE_MODAL",
    OPEN_MODAL: "OPEN_MODAL",
    POST_SCREAM: "POST_SCREAM",
    GET_SINGLE_SCREAM: "GET_SINGLE_SCREAM",
    UI_LOADING: "UI_LOADING",
    FETCH_PRESSED_SCREAM_ID: "FETCH_PRESSED_SCREAM_ID",
    POST_COMMENT: "POST_COMMENT",
    SET_SCREAMS_OF_USER: "SET_SCREAMS_OF_USER",
    GET_USER_INFO: "GET_USER_INFO"
};