export default {
    GET_USER_ID: "GET_USER_ID",
    GET_USER_TOKEN: "GET_USER_TOKEN",
    GET_USER_NAME: "GET_USER_NAME",
    SIGN_USER_OUT: "SIGN_USER_OUT",
    GET_FBITOKEN: "GET_FBITOKEN",
    SET_USER: "SET_USER",
    LIKE_SCREAM: "LIKE_SCREAM",
    UNLIKE_SCREAM: "UNLIKE_SCREAM",
    WELCOME: "WELCOME",
    MARK_NOTIFICATIONS_READ:"MARK_NOTIFICATIONS_READ",
    SET_NOTIFICATIONS:"SET_NOTIFICATIONS"
}